[package]
name = "radiation-counter-service"
version = "0.1.0"
authors = ["BH Cho <byunghoon.cho@gmail.com>"]
edition = "2018"

[dependencies]
kubos-service = { git = "https://github.com/Cube-OS/kubos-service" }
rust-i2c = { git = "https://github.com/Cube-OS/rust-i2c" }
radiation-counter-api = { git = "https://github.com/Cube-OS/radiation-counter-api" }
failure = "0.1.2"
juniper =  "0.11"
log = "^0.4.0"
mount = "0.3.0"
syslog = "4.0"
