[radiation-counter-service]
i2c_bus = "/dev/i2c-0"
i2c_addr = '0x32'
udp_socket = '192.168.0.1:8038'
target = '192.168.0.2:8038'

# Space Segment
[radiation-counter-service.addr]
ip = "0.0.0.0"
port = 8038