[build]
target = "armv7-unknown-linux-musleabihf"
[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"


# target = "armv7-unknown-linux-gnueabihf"
# [target.armv7-unknown-linux-c]
# [target.armv7-unknown-linux-gnueabihf]
# linker = "arm-none-linux-gnueabihf-gcc"

